Added a file which states the properties and method of arrays
inspirezonetech/TeachMeJavaScriptLikeIm5 pull request #81
Opened 2022-10-15 18:40 UTC by rishabh1911007

## Please fill in this pull request template before submitting 

### 1. This pull request resolves #77

### 2. Description
I added a file in folder (3-arrays) which states the properties method of arrays

### 3. Fill in checklist by marking [x]

- [x ] I've read the CONTRIBUTING.md
- [x ] I was assigned to this issue
- [x ] My code is formatted using required linting
- [x ] I've run my code locally and checked it works

2022-10-16 21:29 UTC, sabderemane requested changes

2022-10-16 21:29 UTC, sabderemane commented on 3-arrays/properties and methods of arrays.js
> +// Some properties and methods of array are--
You should rename the file with no spaces please : `array-properties.js`

2022-10-16 21:29 UTC, sabderemane commented on 3-arrays/properties and methods of arrays.js
> +// 1. Returns the number of elements-
```suggestion
// 1. Returns the number of elements :
```

2022-10-16 21:29 UTC, sabderemane commented on 3-arrays/properties and methods of arrays.js
> +//example--
```suggestion
// example
```

2022-10-16 21:29 UTC, sabderemane commented on 3-arrays/properties and methods of arrays.js
> +//example--
```suggestion
// 2. Sorts the array :

		//sort();

// example
```

2022-10-16 21:29 UTC, sabderemane commented on 3-arrays/properties and methods of arrays.js
> +// Some properties and methods of array are--
```suggestion
// Some properties and methods of array are :
```
You should explain what is a property and a method, the syntax of them

2022-10-16 21:29 UTC, sabderemane commented on 3-arrays/properties and methods of arrays.js
> +//example--
```suggestion
// 3. Joins arrays and returns an array with the joined arrays :

		//concat();

// example
```

2022-10-16 21:29 UTC, sabderemane commented on 3-arrays/properties and methods of arrays.js
> +//example--
```suggestion
// 4. Joins all elements of an array into a string :

		//join();

// example
```

2022-10-16 21:29 UTC, sabderemane commented on 3-arrays/properties and methods of arrays.js
> +//example--
```suggestion
// 5. Search the array for an element and returns its position :

		//indexOf();

// example
```

2022-10-16 21:30 UTC, sabderemane commented
Thank you for your contribution @rishabh1911007, I have made some suggestions :)

2022-10-17 03:58 UTC, rishabh1911007 reviewed
Please Just add Hacktoberfest-Accepted Label.

2022-10-17 04:00 UTC, rishabh1911007 reviewed
Please just add Hacktoberfest-accepted label.

2022-10-18 17:12 UTC, rishabh1911007 commented
Now, please add Hacktoberfest-Accepted Label.

2022-10-18 17:32 UTC, sabderemane requested changes
It's missing a challenge as it is said in the CONTRIBUTING.md file. Please review your contribution or it will not be merged.

2022-10-18 18:19 UTC, rishabh1911007 reviewed
Now is it okay ?

2022-10-18 18:20 UTC, rishabh1911007 reviewed
Now is it okay ?

2022-10-18 19:23 UTC, rishabh1911007 commented
Now is it okay, please see it and please do add label of
Hacktoberfest2022-Accepted

On Tue, Oct 18, 2022 at 11:02 PM Sarah Abderemane ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> It's missing a challenge as it is said in the CONTRIBUTING.md file. Please
> review your contribution or it will not be merged.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/inspirezonetech/TeachMeJavaScriptLikeIm5/pull/81#pullrequestreview-1146251806>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV7BKUIVTREBH2UNADPFL2DWD3NMJANCNFSM6AAAAAARGAPANA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2022-10-18 20:18 UTC, sabderemane requested changes
I'm sorry but it's not ok. Please stop putting pressure on the reviewers it will not make the review go faster

2022-10-18 20:18 UTC, sabderemane commented on 3-arrays/properties_and_methods_of_arrays.js
> +fruits.length=3;
```suggestion
console.log(fruits.length); // output : 3
```

2022-10-18 20:18 UTC, sabderemane commented on 3-arrays/properties_and_methods_of_arrays.js
> +fruits.sort();
You should add the output of the sort to show the difference

2022-10-18 20:18 UTC, sabderemane commented on 3-arrays/properties_and_methods_of_arrays.js
> +fruits.concat();
You are doing a concat with nothing, it's not helpful for someone who is learning

2022-10-18 20:18 UTC, sabderemane commented on 3-arrays/properties_and_methods_of_arrays.js
> +fruits.join();
You are using the join method with nothing, not helpful for the learner. You should add the output also.

2022-10-18 20:18 UTC, sabderemane commented on 3-arrays/properties_and_methods_of_arrays.js
> +fruits.indexOf();
You didn't put a specific index and no output also for the learner it's useless

2022-10-19 07:27 UTC, rishabh1911007 reviewed
Updated file of properties and method of arrays.

2022-10-23 23:53 UTC, sabderemane approved these changes

2022-10-23 23:54 UTC, merged

2022-10-23 23:55 UTC, sabderemane commented
Thank you for your contribution @rishabh1911007 ! 🔥